<?xml version='1.0' encoding='UTF-8'?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
  <channel>
    <title>CVE Feed for Python Software Foundation -- CPython</title>
    <link>https://raw.githubusercontent.com/deepseas/cvelistV5monitor/main/feeds/python%20software%20foundation/cpython.rss</link>
    <description>The latest CVEs for Python Software Foundation -- CPython</description>
    <docs>http://www.rssboard.org/rss-specification</docs>
    <generator>python-feedgen</generator>
    <lastBuildDate>Thu, 01 Aug 2024 21:22:38 +0000</lastBuildDate>
    <ttl>60</ttl>
    <item>
      <title>CVE-2024-3219|2024-08-01T20:05:08.371Z -- python%20software%20foundation -- cpython
</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-3219</link>
      <description>There is a MEDIUM severity vulnerability affecting CPython.

The
 “socket” module provides a pure-Python fallback to the 
socket.socketpair() function for platforms that don’t support AF_UNIX, 
such as Windows. This pure-Python implementation uses AF_INET or 
AF_INET6 to create a local connected pair of sockets. The connection 
between the two sockets was not verified before passing the two sockets 
back to the user, which leaves the server socket vulnerable to a 
connection race from a malicious local peer.

Platforms that support AF_UNIX such as Linux and macOS are not affected by this vulnerability. Versions prior to CPython 3.5 are not affected due to the vulnerable API not being included.</description>
      <guid isPermaLink="false">CVE-2024-3219|2024-08-01T20:05:08.371Z</guid>
      <pubDate>Mon, 29 Jul 2024 21:54:05 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-4030|2024-08-01T20:26:57.265Z -- python%20software%20foundation -- cpython
</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-4030</link>
      <description>On Windows a directory returned by tempfile.mkdtemp() would not always have permissions set to restrict reading and writing to the temporary directory by other users, instead usually inheriting the correct permissions from the default location. Alternate configurations or users without a profile directory may not have the intended permissions.

If you’re not using Windows or haven’t changed the temporary directory location then you aren’t affected by this vulnerability. On other platforms the returned directory is consistently readable and writable only by the current user.

This issue was caused by Python not supporting Unix permissions on Windows. The fix adds support for Unix “700” for the mkdir function on Windows which is used by mkdtemp() to ensure the newly created directory has the proper permissions.
</description>
      <guid isPermaLink="false">CVE-2024-4030|2024-08-01T20:26:57.265Z</guid>
      <pubDate>Tue, 07 May 2024 21:02:55 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-4032|2024-08-01T20:26:57.360Z -- python%20software%20foundation -- cpython
</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-4032</link>
      <description>The “ipaddress” module contained incorrect information about whether certain IPv4 and IPv6 addresses were designated as “globally reachable” or “private”. This affected the is_private and is_global properties of the ipaddress.IPv4Address, ipaddress.IPv4Network, ipaddress.IPv6Address, and ipaddress.IPv6Network classes, where values wouldn’t be returned in accordance with the latest information from the IANA Special-Purpose Address Registries.

CPython 3.12.4 and 3.13.0a6 contain updated information from these registries and thus have the intended behavior.</description>
      <guid isPermaLink="false">CVE-2024-4032|2024-08-01T20:26:57.360Z</guid>
      <pubDate>Mon, 17 Jun 2024 15:05:58 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-6923|2024-08-01T14:29:51.269Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-6923</link>
      <description>There is a MEDIUM severity vulnerability affecting CPython.

The 
email module didn’t properly quote newlines for email headers when 
serializing an email message allowing for header injection when an email
 is serialized.</description>
      <guid isPermaLink="false">CVE-2024-6923|2024-08-01T14:29:51.269Z</guid>
      <pubDate>Thu, 01 Aug 2024 13:40:11 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-3219|2024-07-31T18:45:11.922Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-3219</link>
      <description>There is a MEDIUM severity vulnerability affecting CPython.

The
 “socket” module provides a pure-Python fallback to the 
socket.socketpair() function for platforms that don’t support AF_UNIX, 
such as Windows. This pure-Python implementation uses AF_INET or 
AF_INET6 to create a local connected pair of sockets. The connection 
between the two sockets was not verified before passing the two sockets 
back to the user, which leaves the server socket vulnerable to a 
connection race from a malicious local peer.

Platforms that support AF_UNIX such as Linux and macOS are not affected by this vulnerability. Versions prior to CPython 3.5 are not affected due to the vulnerable API not being included.</description>
      <guid isPermaLink="false">CVE-2024-3219|2024-07-31T18:45:11.922Z</guid>
      <pubDate>Mon, 29 Jul 2024 21:54:05 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-3219|2024-07-29T21:58:59.074Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-3219</link>
      <description>There is a MEDIUM severity vulnerability affecting CPython.

The
 “socket” module provides a pure-Python fallback to the 
socket.socketpair() function for platforms that don’t support AF_UNIX, 
such as Windows. This pure-Python implementation uses AF_INET or 
AF_INET6 to create a local connected pair of sockets. The connection 
between the two sockets was not verified before passing the two sockets 
back to the user, which leaves the server socket vulnerable to a 
connection race from a malicious local peer.

Platforms that support AF_UNIX such as Linux and macOS are not affected by this vulnerability. Versions prior to CPython 3.5 are not affected due to the vulnerable API not being included.</description>
      <guid isPermaLink="false">CVE-2024-3219|2024-07-29T21:58:59.074Z</guid>
      <pubDate>Mon, 29 Jul 2024 21:54:05 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2023-6597|2024-07-05T17:22:21.413Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2023-6597</link>
      <description>An issue was found in the CPython `tempfile.TemporaryDirectory` class affecting versions 3.12.1, 3.11.7, 3.10.13, 3.9.18, and 3.8.18 and prior.

The tempfile.TemporaryDirectory class would dereference symlinks during cleanup of permissions-related errors. This means users which can run privileged programs are potentially able to modify permissions of files referenced by symlinks in some circumstances.</description>
      <guid isPermaLink="false">CVE-2023-6597|2024-07-05T17:22:21.413Z</guid>
      <pubDate>Tue, 19 Mar 2024 15:44:28 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-5642|2024-06-28T13:47:48.118Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-5642</link>
      <description>CPython 3.9 and earlier doesn't disallow configuring an empty list ("[]") for SSLContext.set_npn_protocols() which is an invalid value for the underlying OpenSSL API. This results in a buffer over-read when NPN is used (see CVE-2024-5535 for OpenSSL). This vulnerability is of low severity due to NPN being not widely used and specifying an empty list likely being uncommon in-practice (typically a protocol name would be configured).</description>
      <guid isPermaLink="false">CVE-2024-5642|2024-06-28T13:47:48.118Z</guid>
      <pubDate>Thu, 27 Jun 2024 21:05:31 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-5642|2024-06-27T21:10:41.861Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-5642</link>
      <description>CPython 3.9 and earlier doesn't disallow configuring an empty list ("[]") for SSLContext.set_npn_protocols() which is an invalid value for the underlying OpenSSL API. This results in a buffer over-read when NPN is used (see CVE-2024-5535 for OpenSSL). This vulnerability is of low severity due to NPN being not widely used and specifying an empty list likely being uncommon in-practice (typically a protocol name would be configured).</description>
      <guid isPermaLink="false">CVE-2024-5642|2024-06-27T21:10:41.861Z</guid>
      <pubDate>Thu, 27 Jun 2024 21:05:31 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-0397|2024-06-17T15:11:16.322Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-0397</link>
      <description>A defect was discovered in the Python “ssl” module where there is a memory
race condition with the ssl.SSLContext methods “cert_store_stats()” and
“get_ca_certs()”. The race condition can be triggered if the methods are
called at the same time as certificates are loaded into the SSLContext,
such as during the TLS handshake with a certificate directory configured.
This issue is fixed in CPython 3.10.14, 3.11.9, 3.12.3, and 3.13.0a5.</description>
      <guid isPermaLink="false">CVE-2024-0397|2024-06-17T15:11:16.322Z</guid>
      <pubDate>Mon, 17 Jun 2024 15:09:40 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-4032|2024-06-17T15:11:36.402Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-4032</link>
      <description>The “ipaddress” module contained incorrect information about whether certain IPv4 and IPv6 addresses were designated as “globally reachable” or “private”. This affected the is_private and is_global properties of the ipaddress.IPv4Address, ipaddress.IPv4Network, ipaddress.IPv6Address, and ipaddress.IPv6Network classes, where values wouldn’t be returned in accordance with the latest information from the IANA Special-Purpose Address Registries.

CPython 3.12.4 and 3.13.0a6 contain updated information from these registries and thus have the intended behavior.</description>
      <guid isPermaLink="false">CVE-2024-4032|2024-06-17T15:11:36.402Z</guid>
      <pubDate>Mon, 17 Jun 2024 15:05:58 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2023-6597|2024-04-03T15:06:30.430Z -- python%20software%20foundation -- cpython</title>
      <link>https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-6597</link>
      <description>An issue was found in the CPython `tempfile.TemporaryDirectory` class affecting versions 3.12.1, 3.11.7, 3.10.13, 3.9.18, and 3.8.18 and prior.

The tempfile.TemporaryDirectory class would dereference symlinks during cleanup of permissions-related errors. This means users which can run privileged programs are potentially able to modify permissions of files referenced by symlinks in some circumstances.</description>
      <guid isPermaLink="false">CVE-2023-6597|2024-04-03T15:06:30.430Z</guid>
      <pubDate>Tue, 19 Mar 2024 15:44:28 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-0450|2024-05-07T21:47:33.040Z -- python%20software%20foundation -- cpython</title>
      <link>https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-0450</link>
      <description>An issue was found in the CPython `zipfile` module affecting versions 3.12.1, 3.11.7, 3.10.13, 3.9.18, and 3.8.18 and prior.

The zipfile module is vulnerable to “quoted-overlap” zip-bombs which exploit the zip format to create a zip-bomb with a high compression ratio. The fixed versions of CPython makes the zipfile module reject zip archives which overlap entries in the archive.</description>
      <guid isPermaLink="false">CVE-2024-0450|2024-05-07T21:47:33.040Z</guid>
      <pubDate>Tue, 19 Mar 2024 15:12:07 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-4030|2024-06-04T17:55:02.857Z -- python%20software%20foundation -- cpython</title>
      <link>https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-4030</link>
      <description>On Windows a directory returned by tempfile.mkdtemp() would not always have permissions set to restrict reading and writing to the temporary directory by other users, instead usually inheriting the correct permissions from the default location. Alternate configurations or users without a profile directory may not have the intended permissions.

If you’re not using Windows or haven’t changed the temporary directory location then you aren’t affected by this vulnerability. On other platforms the returned directory is consistently readable and writable only by the current user.

This issue was caused by Python not supporting Unix permissions on Windows. The fix adds support for Unix “700” for the mkdir function on Windows which is used by mkdtemp() to ensure the newly created directory has the proper permissions.</description>
      <guid isPermaLink="false">CVE-2024-4030|2024-06-04T17:55:02.857Z</guid>
      <pubDate>Tue, 07 May 2024 21:02:55 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-0450|2024-06-13T19:24:15.993Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-0450</link>
      <description>An issue was found in the CPython `zipfile` module affecting versions 3.12.1, 3.11.7, 3.10.13, 3.9.18, and 3.8.18 and prior.

The zipfile module is vulnerable to “quoted-overlap” zip-bombs which exploit the zip format to create a zip-bomb with a high compression ratio. The fixed versions of CPython makes the zipfile module reject zip archives which overlap entries in the archive.</description>
      <guid isPermaLink="false">CVE-2024-0450|2024-06-13T19:24:15.993Z</guid>
      <pubDate>Tue, 19 Mar 2024 15:12:07 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2023-6597|2024-06-13T19:24:11.289Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2023-6597</link>
      <description>An issue was found in the CPython `tempfile.TemporaryDirectory` class affecting versions 3.12.1, 3.11.7, 3.10.13, 3.9.18, and 3.8.18 and prior.

The tempfile.TemporaryDirectory class would dereference symlinks during cleanup of permissions-related errors. This means users which can run privileged programs are potentially able to modify permissions of files referenced by symlinks in some circumstances.</description>
      <guid isPermaLink="false">CVE-2023-6597|2024-06-13T19:24:11.289Z</guid>
      <pubDate>Tue, 19 Mar 2024 15:44:28 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-4030|2024-06-13T19:24:24.254Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-4030</link>
      <description>On Windows a directory returned by tempfile.mkdtemp() would not always have permissions set to restrict reading and writing to the temporary directory by other users, instead usually inheriting the correct permissions from the default location. Alternate configurations or users without a profile directory may not have the intended permissions.

If you’re not using Windows or haven’t changed the temporary directory location then you aren’t affected by this vulnerability. On other platforms the returned directory is consistently readable and writable only by the current user.

This issue was caused by Python not supporting Unix permissions on Windows. The fix adds support for Unix “700” for the mkdir function on Windows which is used by mkdtemp() to ensure the newly created directory has the proper permissions.</description>
      <guid isPermaLink="false">CVE-2024-4030|2024-06-13T19:24:24.254Z</guid>
      <pubDate>Tue, 07 May 2024 21:02:55 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-0397|2024-06-20T16:08:46.179Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-0397</link>
      <description>A defect was discovered in the Python “ssl” module where there is a memory
race condition with the ssl.SSLContext methods “cert_store_stats()” and
“get_ca_certs()”. The race condition can be triggered if the methods are
called at the same time as certificates are loaded into the SSLContext,
such as during the TLS handshake with a certificate directory configured.
This issue is fixed in CPython 3.10.14, 3.11.9, 3.12.3, and 3.13.0a5.</description>
      <guid isPermaLink="false">CVE-2024-0397|2024-06-20T16:08:46.179Z</guid>
      <pubDate>Mon, 17 Jun 2024 15:09:40 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-5642|2024-06-27T22:13:17.948Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-5642</link>
      <description>CPython 3.9 and earlier doesn't disallow configuring an empty list ("[]") for SSLContext.set_npn_protocols() which is an invalid value for the underlying OpenSSL API. This results in a buffer over-read when NPN is used (see CVE-2024-5535 for OpenSSL). This vulnerability is of low severity due to NPN being not widely used and specifying an empty list likely being uncommon in-practice (typically a protocol name would be configured).</description>
      <guid isPermaLink="false">CVE-2024-5642|2024-06-27T22:13:17.948Z</guid>
      <pubDate>Thu, 27 Jun 2024 21:05:31 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-5642|2024-07-01T13:51:32.404Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-5642</link>
      <description>CPython 3.9 and earlier doesn't disallow configuring an empty list ("[]") for SSLContext.set_npn_protocols() which is an invalid value for the underlying OpenSSL API. This results in a buffer over-read when NPN is used (see CVE-2024-5535 for OpenSSL). This vulnerability is of low severity due to NPN being not widely used and specifying an empty list likely being uncommon in-practice (typically a protocol name would be configured).</description>
      <guid isPermaLink="false">CVE-2024-5642|2024-07-01T13:51:32.404Z</guid>
      <pubDate>Thu, 27 Jun 2024 21:05:31 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-3219|2024-07-29T21:55:38.610Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-3219</link>
      <description>There is a MEDIUM severity vulnerability affecting CPython.

The
 “socket” module provides a pure-Python fallback to the 
socket.socketpair() function for platforms that don’t support AF_UNIX, 
such as Windows. This pure-Python implementation uses AF_INET or 
AF_INET6 to create a local connected pair of sockets. The connection 
between the two sockets was not verified before passing the two sockets 
back to the user, which leaves the server socket vulnerable to a 
connection race from a malicious local peer.

Platforms that support AF_UNIX such as Linux and macOS are not affected by this vulnerability. Versions prior to CPython 3.5 are not affected due to the vulnerable API not being included.</description>
      <guid isPermaLink="false">CVE-2024-3219|2024-07-29T21:55:38.610Z</guid>
      <pubDate>Mon, 29 Jul 2024 21:54:05 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-3219|2024-07-30T12:45:56.043Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-3219</link>
      <description>There is a MEDIUM severity vulnerability affecting CPython.

The
 “socket” module provides a pure-Python fallback to the 
socket.socketpair() function for platforms that don’t support AF_UNIX, 
such as Windows. This pure-Python implementation uses AF_INET or 
AF_INET6 to create a local connected pair of sockets. The connection 
between the two sockets was not verified before passing the two sockets 
back to the user, which leaves the server socket vulnerable to a 
connection race from a malicious local peer.

Platforms that support AF_UNIX such as Linux and macOS are not affected by this vulnerability. Versions prior to CPython 3.5 are not affected due to the vulnerable API not being included.</description>
      <guid isPermaLink="false">CVE-2024-3219|2024-07-30T12:45:56.043Z</guid>
      <pubDate>Mon, 29 Jul 2024 21:54:05 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-6923|2024-08-01T13:40:11.069Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-6923</link>
      <description>There is a MEDIUM severity vulnerability affecting CPython.

The 
email module didn’t properly quote newlines for email headers when 
serializing an email message allowing for header injection when an email
 is serialized.</description>
      <guid isPermaLink="false">CVE-2024-6923|2024-08-01T13:40:11.069Z</guid>
      <pubDate>Thu, 01 Aug 2024 13:40:11 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-3219|2024-08-01T13:43:17.624Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-3219</link>
      <description>There is a MEDIUM severity vulnerability affecting CPython.

The
 “socket” module provides a pure-Python fallback to the 
socket.socketpair() function for platforms that don’t support AF_UNIX, 
such as Windows. This pure-Python implementation uses AF_INET or 
AF_INET6 to create a local connected pair of sockets. The connection 
between the two sockets was not verified before passing the two sockets 
back to the user, which leaves the server socket vulnerable to a 
connection race from a malicious local peer.

Platforms that support AF_UNIX such as Linux and macOS are not affected by this vulnerability. Versions prior to CPython 3.5 are not affected due to the vulnerable API not being included.</description>
      <guid isPermaLink="false">CVE-2024-3219|2024-08-01T13:43:17.624Z</guid>
      <pubDate>Mon, 29 Jul 2024 21:54:05 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-6923|2024-08-01T18:18:12.965Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-6923</link>
      <description>There is a MEDIUM severity vulnerability affecting CPython.

The 
email module didn’t properly quote newlines for email headers when 
serializing an email message allowing for header injection when an email
 is serialized.</description>
      <guid isPermaLink="false">CVE-2024-6923|2024-08-01T18:18:12.965Z</guid>
      <pubDate>Thu, 01 Aug 2024 13:40:11 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-0397|2024-08-01T18:04:49.771Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-0397</link>
      <description>A defect was discovered in the Python “ssl” module where there is a memory
race condition with the ssl.SSLContext methods “cert_store_stats()” and
“get_ca_certs()”. The race condition can be triggered if the methods are
called at the same time as certificates are loaded into the SSLContext,
such as during the TLS handshake with a certificate directory configured.
This issue is fixed in CPython 3.10.14, 3.11.9, 3.12.3, and 3.13.0a5.</description>
      <guid isPermaLink="false">CVE-2024-0397|2024-08-01T18:04:49.771Z</guid>
      <pubDate>Mon, 17 Jun 2024 15:09:40 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2024-0450|2024-08-01T18:04:49.775Z -- python%20software%20foundation -- cpython</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2024-0450</link>
      <description>An issue was found in the CPython `zipfile` module affecting versions 3.12.1, 3.11.7, 3.10.13, 3.9.18, and 3.8.18 and prior.

The zipfile module is vulnerable to “quoted-overlap” zip-bombs which exploit the zip format to create a zip-bomb with a high compression ratio. The fixed versions of CPython makes the zipfile module reject zip archives which overlap entries in the archive.</description>
      <guid isPermaLink="false">CVE-2024-0450|2024-08-01T18:04:49.775Z</guid>
      <pubDate>Tue, 19 Mar 2024 15:12:07 +0000</pubDate>
    </item>
  </channel>
</rss>
