<?xml version='1.0' encoding='UTF-8'?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
  <channel>
    <title>CVE Feed for gitpython-developers -- GitPython</title>
    <link>https://raw.githubusercontent.com/deepseas/cvelistV5monitor/main/feeds/gitpython-developers/gitpython.rss</link>
    <description>The latest CVEs for gitpython-developers -- GitPython</description>
    <docs>http://www.rssboard.org/rss-specification</docs>
    <generator>python-feedgen</generator>
    <lastBuildDate>Tue, 01 Oct 2024 21:23:26 +0000</lastBuildDate>
    <ttl>60</ttl>
    <item>
      <title>CVE-2023-41040|2024-10-01T18:04:56.017Z -- gitpython-developers -- gitpython
</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2023-41040</link>
      <description>GitPython is a python library used to interact with Git repositories. In order to resolve some git references, GitPython reads files from the `.git` directory, in some places the name of the file being read is provided by the user, GitPython doesn't check if this file is located outside the `.git` directory. This allows an attacker to make GitPython read any file from the system. This vulnerability is present in https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175. That code joins the base directory with a user given string without checking if the final path is located outside the base directory. This vulnerability cannot be used to read the contents of files but could in theory be used to trigger a denial of service for the program. This issue has been addressed in version 3.1.37.</description>
      <guid isPermaLink="false">CVE-2023-41040|2024-10-01T18:04:56.017Z</guid>
      <pubDate>Wed, 30 Aug 2023 21:07:42 +0000</pubDate>
    </item>
  </channel>
</rss>
