<?xml version='1.0' encoding='UTF-8'?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0"><channel><title>CVE Feed for pyca -- all</title><link>https://raw.githubusercontent.com/deepseas/cvelistV5monitor/main/feeds/pyca/all.rss</link><description>The latest CVEs for pyca -- all</description><docs>http://www.rssboard.org/rss-specification</docs><generator>python-feedgen</generator><lastBuildDate>Fri, 31 May 2024 16:28:19 +0000</lastBuildDate><ttl>60</ttl><item><title>CVE-2024-26130|2024-02-21T16:28:18.632Z -- pyca -- cryptography
</title><link>https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-26130</link><description>cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. Starting in version 38.0.0 and prior to version 42.0.4, if `pkcs12.serialize_key_and_certificates` is called with both a certificate whose public key did not match the provided private key and an `encryption_algorithm` with `hmac_hash` set (via `PrivateFormat.PKCS12.encryption_builder().hmac_hash(...)`, then a NULL pointer dereference would occur, crashing the Python process. This has been resolved in version 42.0.4, the first version in which a `ValueError` is properly raised.</description><guid isPermaLink="false">CVE-2024-26130|2024-02-21T16:28:18.632Z</guid><pubDate>Wed, 21 Feb 2024 16:28:18 +0000</pubDate></item></channel></rss>