<?xml version='1.0' encoding='UTF-8'?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0"><channel><title>CVE Feed for jupyterhub -- jupyter-server-proxy</title><link>https://raw.githubusercontent.com/deepseas/cvelistV5monitor/main/feeds/jupyterhub/jupyter-server-proxy.rss</link><description>The latest CVEs for jupyterhub -- jupyter-server-proxy</description><docs>http://www.rssboard.org/rss-specification</docs><generator>python-feedgen</generator><lastBuildDate>Tue, 28 May 2024 22:02:46 +0000</lastBuildDate><ttl>60</ttl><item><title>CVE-2024-28179|2024-03-20T19:54:38.247Z -- jupyterhub -- jupyter-server-proxy
</title><link>https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-28179</link><description>Jupyter Server Proxy allows users to run arbitrary external processes alongside their Jupyter notebook servers and provides authenticated web access. Prior to versions 3.2.3 and 4.1.1, Jupyter Server Proxy did not check user authentication appropriately when proxying websockets, allowing unauthenticated access to anyone who had network access to the Jupyter server endpoint. This vulnerability can allow unauthenticated remote access to any websocket endpoint set up to be accessible via Jupyter Server Proxy. In many cases, this leads to remote unauthenticated arbitrary code execution, due to how affected instances use websockets. The websocket endpoints exposed by `jupyter_server` itself is not affected. Projects that do not rely on websockets are also not affected. Versions 3.2.3 and 4.1.1 contain a fix for this issue.</description><guid isPermaLink="false">CVE-2024-28179|2024-03-20T19:54:38.247Z</guid><pubDate>Wed, 20 Mar 2024 19:54:38 +0000</pubDate></item></channel></rss>